"""Campaign Insight Agent package — structured analytics subgraph."""
from agents.campaign_insight.contracts import (
    AgentStatus,
    DimensionClassification,
    DimensionConfig,
    DimensionRole,
    DisplayTable,
    ExecutionPlan,
    GenieResponse,
    Interpretation,
    PatternMatch,
    PlanStep,
    Recommendation,
    StepResult,
    StepStatus,
    SubagentInput,
    SubagentOutput,
    TableSummary,
    VerificationResult,
)

__all__ = [
    "AgentStatus",
    "DimensionClassification",
    "DimensionConfig",
    "DimensionRole",
    "DisplayTable",
    "ExecutionPlan",
    "GenieResponse",
    "Interpretation",
    "PatternMatch",
    "PlanStep",
    "Recommendation",
    "StepResult",
    "StepStatus",
    "SubagentInput",
    "SubagentOutput",
    "TableSummary",
    "VerificationResult",
]
